-- MySQL Script generated by MySQL Workbench
-- jeu 26 déc 2019 16:06:57 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iot` DEFAULT CHARACTER SET utf8 ;
USE `iot` ;

-- -----------------------------------------------------
-- Table `iot`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`Room` ;

CREATE TABLE IF NOT EXISTS `iot`.`Room` (
  `number` INT NOT NULL,
  PRIMARY KEY (`number`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iot`.`Beacon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iot`.`Beacon` ;

CREATE TABLE IF NOT EXISTS `iot`.`Beacon` (
  `uuid` VARCHAR(255) NOT NULL,
  `major` INT NOT NULL,
  `minor` INT NOT NULL,
  `room_number` INT NOT NULL,
  PRIMARY KEY (`uuid`, `major`, `minor`, `room_number`),
  INDEX `fk_Beacon_Room_idx` (`room_number` ASC),
  CONSTRAINT `fk_Beacon_Room`
    FOREIGN KEY (`room_number`)
    REFERENCES `iot`.`Room` (`number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------

INSERT INTO `iot`.`Room` (`number`) VALUES (10);
INSERT INTO `iot`.`Room` (`number`) VALUES (20);

INSERT INTO `iot`.`Beacon` (`uuid`, `major`, `minor`, `room_number`) VALUES ('b9407f30-f5f8-466e-aff9-25556b57fe6d', 17644, 12302, 10);
INSERT INTO `iot`.`Beacon` (`uuid`, `major`, `minor`, `room_number`) VALUES ('b9407f30-f5f8-466e-aff9-25556b57fe6d', 17644, 31456, 20);
